interactivethings/catalog

- docs/react/overview.md
- src/__tests__/configure-test.js
- src/__tests__/configureRoutes-test.js
- src/components/Card/Card.js
- src/configure.js
- src/configureRoutes.js
- src/render.js
- src/utils/warning.js
Threre's no need to expose the `configure` function. Just use `configureRoutes` directly.
> [WIP] Simplify Configuration

- src/CatalogPropTypes.js
- src/__tests__/configure-test.js
- src/components/CatalogContext.js
- src/components/Menu/Menu.js
- src/configure.js
Right now, the sidebar logo always points to / , but it should rather be the basePath if provided. I was not sure what the difference is between path and basePath, so it might need to be adjusted for that.
> Link to basepath

- src/specimens/Hint.js
Addresses #91, but only regarding the hint.
> allow jsx in hint specimen

- package.json
- src/specimens/ColorPalette.js
Addresses #89, implementation of the initial proposal
> Color contrast

- src/components/Frame/FrameComponent.js
Uses the experimental `ReactDOM.unstable_renderSubtreeIntoContainer` which is the only way to pass context to a detached subtree (usually rendered with `ReactDOM.render`.
Also cleaned up and linted the syntax.
Fixes #118
> Make sure context is passed to framed specimen components

- src/components/Frame/FrameComponent.js
Only pass selected props to the iframe, and add them to PropTypes of the
FrameComponent component.
> Warning: Unknown props `head`, `onRender` on <iframe> tag.

- .gitignore
- src/specimens/Table.js
Vertically align and pad table cells on right.
> Cell padding

- .gitignore
- docs/specimens/html.md
- docs/specimens/image.md
- docs/specimens/table.md
- docs/specimens/type.md
I tried to clarify the things I didn't understand. I also re-introduced
the "old" way of specifying props because we either use tables for prop
definitions everywhere or nowhere, but not just here. I found this to be
confusing at first.
> Improve table docs

- src/loader.js
:fire: :fire: :fire: :fire: :fire:
> fixed path sep escape char issue on windows

- src/specimens/Code.js
- src/specimens/Hint.js
- src/specimens/Type.js
- src/utils/path.js
- src/utils/path.test.js
Fixes a regression introduced in #165.
> Fix index path when basePath is set

- src/components/App/AppLayout.js
- src/components/Menu/Menu.js
- src/components/ResponsiveTabs/ResponsiveTabs.js
- src/specimens/ColorPalette.js
- src/specimens/Download.js
- src/specimens/Image.js
- src/specimens/Table.js
Before:
After:
Addresses #191 (I don't think we can actually make it work in IE9 though)
> IE11 fixes

- src/specimens/ReactSpecimen/ReactSpecimen.js
- src/specimens/ReactSpecimen/reactElementToString.js
- src/specimens/ReactSpecimen/reactElementToString.test.js
The whole algorithm could use an overhaul (something like https://github.com/facebook/jest/tree/master/packages/pretty-format) but for now I fixed the most immediate errors reported by @wereHamster.
> React element stringification fixes

- src/utils/validateSizes.test.js
Thanks for merging. Noticed a small reference error in the test I wrote, here a fix.
> Fix validate sizes test ref

- package.json
- yarn.lock
Fixes #352 
Supersedes #353 (use marked 3.0.12 and also update yarn.lock)
> Upgrade marked

- src/styles/typography.js
This PR will fix the default browser style applied to visited links. At the moment the custom link color is not applied to visited links.
> fix: Fix links visited color to prevent default style.

- src/components/Frame/Frame.js
- src/components/Frame/FrameComponent.js
- src/components/ResponsiveTabs/ResponsiveTabs.js
- src/specimens/Html.js
- src/specimens/ReactSpecimen/ReactSpecimen.js
Resolves #371.
I also improved the appearance of the responsive specimens by limiting the checkerboard pattern to the frame itself.
> Iframe improvements

- src/utils/parseSpecimenBody.js
- src/utils/parseSpecimenBody.test.js
> Make separator whitespace insensitive in parseSpecimenBody

- docs/test/test.md
- package.json
- src/markdown/marked-react.js
- yarn.lock
> Fix Markdown links

- src/markdown/__snapshots__/renderMarkdown.test.js.snap
- src/markdown/marked-react.js
- src/markdown/renderMarkdown.test.js
Fixes regressions introduced in #436
> More markdown fixes

- docs/installation/module.md
> typo fix on module usage

- src/specimens/Table.js
> Fix table head style typo
