- docs/specimens/overview.md
- src/components/Specimen/Specimen.js
- src/specimens/Code.js
- src/specimens/Hint.js
- src/specimens/Html.js
- src/specimens/ReactSpecimen/ReactSpecimen.js
- src/utils/__tests__/parseSpecimenBody-test.js
- src/utils/parseSpecimenBody.js
Before, any Specimen body which contained valid YAML was parsed. That meant also something like `const foo:Bar = 3;` or `<div style={{fontSize: 30}}>foo</div>` was parsed (because of the `:`)!
This PR introduces two changes to this logic:
1. Specimens which only need YAML (e.g. ColorSpecimen), now use a function which only does that
2. Specimens which contain primarily non-YAML content (e.g. CodeSpecimen) now won't attempt to parse any YAML *unless* they contain a frontmatter-like section separated with `---`. This is similar to before but it's a) *opt-in* for specific specimens and b) *only* content before `---` (if present) will be attempted to be parsed.
Fixes #95. Pinging @wereHamster who reported this.
> Fix specimen body parsing

- src/CatalogPropTypes.js
- src/components/App/App.js
- src/components/App/AppLayout.js
- src/components/App/NavigationBar.js
- src/components/CatalogContext.js
- src/components/Menu/ListItem.js
- src/components/Menu/Menu.js
- src/components/Menu/NestedList.js
- src/components/Page/Page.js
- src/components/Page/PageContentLoader.js
- src/components/Page/PageRenderer.js
- src/components/Specimen/MarkdownSpecimen.js
- src/components/Specimen/Specimen.js
- src/specimens/Audio.js
- src/specimens/Code.js
- src/specimens/Color.js
- src/specimens/ColorPalette.js
- src/specimens/Download.js
- src/specimens/Hint.js
- src/specimens/Html.js
- src/specimens/Image.js
- src/specimens/ReactSpecimen/ReactSpecimen.js
- src/specimens/Type.js
- src/specimens/Video.js
We now define only one `catalog` context object (which contains all previously defined context props). This makes Catalog a better citizen because it doesn't pollute context anymore and it's clearer which context props belong to which library.
Specimens now don't have to use context at all because the current catalog context object will be passed as a prop to them. Before they just received `theme` as a prop which wasn't enough for `ReactSpecimen`. This opens the door for more advanced specimens and also makes them easier to test (once we get to that).
This shouldn't break break anything for users because context is just used internally.
> Refactor Catalog context

- package.json
- src/render.js
Uses the new https://github.com/taion/react-router-scroll router middleware for more reliable scroll handling. This needs react-router@2.3, so I've bumped the required version.
I also moved react-router and history to dependencies, so it's less of a hassle to install Catalog. I'm not 100% sure if this works with `configureRoutes` and older react-router versions though.
> Update React Router and scroll behavior

- package.json
- src/components/App/App.js
Modifies the document title to match the current page's title. E.g.
- Catalog – Overview
- Catalog – Specimens – React
[react-helmet](https://github.com/nfl/react-helmet) would be a more complete solution but adds another 10KB to the minified bundle compared to [react-document-title](https://github.com/gaearon/react-document-title).
Fixes #119
> Dynamic document title

- docs/basics/configuration.md
- docs/basics/get-started.md
- docs/react-integration.md
- examples/catalog-module/index.js
- src/components/Catalog.js
- src/index-standalone.js
- src/index.js
- src/render.js
Wraps `Router` initialization and route configuration in the `Catalog` component. This _should_ improve composability in existing apps which may not use react-router themselves (see #93).
I don't know if this is such a great idea. Since it's a small addition to the external API and doesn't prevent more low-level integration in apps I don't think this would hurt too much. I'm still hesitant to add this, especially if it doesn't solve any real problems.
One thing this _could_ potentially enable is adding a configuration switch between `hashHistory` (currently the only way Catalog does routing unless you use `configureRoutes` and configure the router yourself) and `browserHistory`. I.e. `<Catalog configuration={{browserHistory: true, ...}} />` or pass in your own `history`, but then what's …
> Add Catalog component

- docs/specimens/image.md
- src/specimens/Image.js
- src/utils/renderMarkdown.js
Allow multiple lines in descriptions, style fixes, documentation updates.
Please review @TaniaBoa 😊 
Fixes #255
> Improve image specimen descriptions

- src/components/App/AppLayout.js
- src/components/Frame/Frame.js
- src/specimens/Html.js
- src/specimens/ReactSpecimen/ReactSpecimen.js
In some edge cases, the iframe got scaled twice (e.g. one `transform: scale(0.5)` somehow got applied twice, resulting in an iframe with scale 0.25). Wrapping it in an element with the scale transform *and* defined width and height solved this issue.
To prevent a rendering glitch, the React and HTML specimens now only show the frame after their own width is measured.
> Responsive mode layout fix

- index.html
- src/__snapshots__/configure.test.js.snap
- src/configure.js
- src/configure.test.js
For page groups, the `path` property is unnecessary but Catalog would fail when not provided (regression in 2.5.0).
Fixes #265
> Fix path configuration

- CHANGELOG.md
- package.json
- src/components/Page/PageRenderer.js
- yarn.lock
Resolves #275.
A larger timeout (eg. `setTimeout(…, 16)`) would also solve it. But I think rAF reflects the intention better.
I suspect it's because the page layout is not full complete because Radium injects the styles asynchronously, and a zero timeout is not enough. The element is present in the DOM, but somehow `el.scrollIntoView()` does not work.
> Fix jump to anchor

- docs/basics/configuration.md
- src/configureRoutes.js
- src/fetchMarkdown.js
Now we can support all possible forms of `content`: strings, functions, promises, react components or elements. Strings can be both URLs and inline markdown, automagically handled. And promises can return strings which can be URLs to markdown files. Even cases of complete rubbish configuration (eg. `content: true`) are handled reasonably well.
> Be more open what to accept as page content

- src/specimens/Html.js
The underlying issue was an off-by-2 error when calculating the `parentWidth` (not accounting for the 1px border on both sides). Each resize event would grow the width by 2px.
I also changed `<Frame />` to not affect the width of the parent element. This is needed to allow the frame to shrink when the user resizes the window down. Without that change, the frame can only grow but never shrink.
> Responsive specimen inifinite growth

- CHANGELOG.md
- docs/basics/configuration.md
- docs/react-integration.md
- src/index-standalone.js
- src/index.js
- src/markdownPage.js
- src/markdownPage.test.js
I've made two small changes to the tagged template literal:
- Renamed it to `Catalog.markdown` (`markdown` when imported), mostly because I want editors to treat the string content as markdown and apply the correct syntax highlighting. Currently no editor supports this but I'd like to be future-proof 😄 
- `` markdown`# Foo` `` now returns a function (component) which is more what I'd expect it to do.
So the changed template literal works like this:
```js
import {markdown} from 'catalog'
const MyPage = markdown`
This is a paragraph.
- one
- two
`
```
I've also updated the docs and moved it from the Configuration to the React Integration page.
> Improve tagged template literal

- src/__snapshots__/markdownPage.test.js.snap
- src/markdownPage.js
- src/markdownPage.test.js
In addition to valid React elements, allow strings, numbers and JSON-stringifiable objects. This enables passing in arbitrary data to specimens and Markdown text (e.g. a variable with data).
> Improve markdown template literal

- cli/src/actions/loadConfigFile.js
- cli/src/actions/runDevServer.js
- cli/src/bin/catalog-build.js
- cli/src/bin/catalog-start.js
- cli/src/config/createReactApp.js
Currently supports only the `webpack` option which must be a function that accepts the generated config and must return the modified one. We can add more config options later (merging with defaults and/or CLI options is a bit more complicated and should be properly tested).
Additionally, I've modified the default webpack (CRA-like) config, so that JS files are not only transpiled in `src` but the app root (excluding `node_modules`) to make it easier to integrate with non-CRA setups.
👉  @bebraw @oyeanuj @wereHamster
> Add CLI support for config file

- src/components/Frame/FrameComponent.js
Framed Specimens should also contain the parent page's linked stylesheets in addition to `<style>` elements.
> Clone stylesheet references from parent page into iframes

- src/components/Frame/Frame.js
- src/specimens/Html.js
- src/specimens/ReactSpecimen/ReactSpecimen.js
This should match the user's mental model more closely to what happens in responsive mode (which is supposed to emulate a device). Whereas in framed mode, the intention is just to isolate an element from the parent page, and the specimen is automatically resized anyway.
Fixes #320
> Enable iframe scrolling in responsive mode

- src/components/Menu/NestedList.js
Currently `hideFromMenu` only works for top level pages and page groups. The flag is ignored on nested pages. This should make it respect the flag on any page.
> Make nested pages able to be hidden from menu also

- src/utils/validateSizes.js
- src/utils/validateSizes.test.js
Currently when specifying a specific array of sizes for a specimen the order is not respected and overruled with by the global order of responsive sizes.
IMO the local order should win, allowing to showcase a specific size first.
> Allow to re-order responsive sizes

- src/specimens/Type.js
I saw this in #296 and didn't realize how much I wanted to customize the Type specimen.
The normal type specimen would allow an array of values to generate the previews like this:
```
``type
{
"headings": [49, 38, 27, 24, 21, 19 ],
"paragraphs": ["15/22.5","13/19.5"]
}
``
```
I changed it so that you can also make the array include objects with `label` and `value` keys to customize the label that is shown
```
``type
{
"headings": [
{ "label": "Headline 1", "value": 49},
{ "label": "Headline 2", "value": 38},
{ "label": "Headline 3", "value": 27},
{ "label": "Headline 4", "value": 24},
{ "label": "Headline 5", "value": 21},
{ "label": "Headline 6", "value": 19},
],
"paragraphs": [
{ "label": "Body Copy", "value": "15/22.5"},
{ "label": "Small Text", "value": "13/19.5"}
]
}
``
```
For my …
> Make Type specimen accept arrays for values to customize labels

- src/components/App/AppLayout.js
An attempt to fix this: https://github.com/interactivethings/catalog/issues/345
> Fix #345 — don’t force theme colour on the entire page but just menuIcon.

- src/components/ResponsiveTabs/ResponsiveTabs.js
- src/specimens/Html.js
- src/specimens/ReactSpecimen/ReactSpecimen.js
Fixes #356
- Add `showSource` prop to html specimen to allow rendering with the source already expanded.
- Apply this to the react specimen as well – there is no apparent reason why they should behave differently.
- For multiple columns, the specimen content now fills the available height while the the source is placed at the bottom instead of creating a gap.
> Unify source toggle

- cli/src/actions/loadConfigFile.js
- cli/src/actions/loadWebpackConfig.js
- cli/src/bin/catalog-build.js
- cli/src/bin/catalog-start.js
Sometimes the automatic behavior of using the existing `.babelrc` file is not desired.
In the future I want to make this **opt-in** but this would be a breaking change.
> Add option to enable/disable babelrc

- docs/installation/module.md
Hi!
Going through the docs I noticed there's a link pointing to an unexisting path. This fixes it and points to the currently correct path.
> Fixes Installation React guide link

- docs/configuration/theming.md
I refined the page about theming in the Configuration chapter of our docs. I believe that the extended content is more clear about what you can do and how to do it and that the new table with attributes, default values and application is more user friendly.
> Refine the theming docs
